[package]
name = "cpwire"
version = "0.1.0"
description = "cp|WIRE — cockpit de pilotage Armonie"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2" }

[dependencies]
tauri = { version = "2", features = ["macos-private-api"] }

[profile.release]
opt-level = "s"
lto = true
strip = true
